### ISSUE TITLE
Javscript Error

### ISSUE THREAD

**Issue by florian33** [vehiclefits/vfmagento#11]
Still with a brand new configuration :
In Source Code :
"<b>Parse error</b>:  syntax error, unexpected end of file in <b>C:\xampp\htdocs\bolt\lib\VF\html\Js\submits.js.php</b> on line <b>103</b><br />"

line 95 to 103 in submit.js.php:
"<?php
if( shouldAutoSubmit( $levels ) )
{
    ?>
    jQuery( '.<?=$levels[$c - 1]?>Select').change( function() {
        autoSubmit();
    } );
    <?
}"
In firebug console :
"
SyntaxError: syntax error
[Stopper sur une erreur]  
<br />
js?fro...ns=show (ligne 139, col. 9)

"

**Comment by joshribakoff** [comment]
Can you try to add a closing php tag and see if that fixes? Please include
the output of phpinfo here for us to reproduce

**Comment by florian33** [comment]
It's for the make, model,year search module. It can't load my vehicles.
Here, fix I tried :
<?php } ?> =­> doesn't work !

**Comment by joshribakoff** [comment]
Please show us your phpinfo

**Comment by florian33** [comment]
I fix it :
in my case the error was in line 50
 <?
}
?>
i changed it with 
 <?php
}
?>

no more error but nothing load.

**Comment by kylecannon** [comment]
So you have short tags disabled in your php.ini correct?

**Comment by florian33** [comment]
I don't touch this... 
; short_open_tag
;    Default Value: Off
;   Development Value: Off
;   Production Value: Off

**Comment by kylecannon** [comment]
Opened up issue #12

**Comment by florian33** [comment]
The main problem isn't resolved... Javascript doesn't load my make... I can't search...

**Comment by kylecannon** [comment]
Are there any javascript console errors?

**Comment by florian33** [comment]
No one....i add this in my URL : http://serveur/?make=1&model=1&year=1 and I've got this : 
![My vehicle](https://f.cloud.github.com/assets/666505/411101/0b48e43e-ab81-11e2-9dcd-d7f0593be1f5.png)
Button search and Clear seems to do somethings. the problem is in the select I thing

**Comment by florian33** [comment]
I can't find it... I can change make with the little trick : http://serveur/?make=1&model=1&year=1 but It's not easy. 
I try with Mozilla Firefox and Google Chrome.

**Comment by joshribakoff** [comment]
What can't you find? Enable short tags in php.ini - we will add support for for short tags being disabled in a future commit, see issue #12

**Comment by florian33** [comment]
i can t find how to get search by make model year working ! nothing is loaded in the select make

**Comment by florian33** [comment]
I think, i'v got something wrong. The Url for action in the form "vafForm" is "http://serveur/index.php/vaf/product/list/".
I haven't any folder "vaf" with this name at the root.

**Comment by kylecannon** [comment]
/vaf/ is a controller in magnetos config.xml 
—

**Comment by joshribakoff** [comment]
Florian please send a support ticket and ill upgrade your site tonight.

**Comment by florian33** [comment]
in fact, I saw your file so I create a local test version with new magento install and your module from github to test it. That's why I try to help you with all problems I have. For my compagnie website, It's only merge the 1st world problem and we want to add wheels.

**Comment by joshribakoff** [comment]
I'm not sure what you're saying but v2 is released, and if you want
installation, you do have a support contract so I can set it up and fix
these problems for you, including installation of the wheels module.

On Tue, Apr 23, 2013 at 10:18 AM, Florian33 notifications@github.comwrote:

> in fact, I saw your file so I create a local test version with new magento
> install and your module form github. That's why I try to help you with all
> problems I have. For my compagnie website, It's only merge the 1st world
> problem and we want to add wheels.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/vehiclefits/Vehicle-Fits-Magento/issues/11#issuecomment-16860748
> .

## 

Josh Ribakoff
www.vehiclefits.com
1-877-CAR-1788

**Comment by florian33** [comment]
Yes, I know it, that's why i ask you to send us informations about pricing and what's that include.
#ZXH-842-45823 ticket. 

For my javascript problem, i can't fix it. i'll try to get it working with new install.

**Comment by joshribakoff** [comment]
You already have support there is no charge for you. Just email
support@vehiclefits.com

**Comment by florian33** [comment]
Excellent.
Have you an idea why the select can't load my makes ? I would try to fix it.

**Comment by kylecannon** [comment]
Please post some screenshots of your network tab and show us what javascript files are being loaded along with the javascript console to see if there are any errors.

**Comment by florian33** [comment]
![make exist](https://f.cloud.github.com/assets/666505/416173/fe223ea6-ac46-11e2-86ad-861d979eed51.jpg)
Just to show that one make is created
![firebug console](https://f.cloud.github.com/assets/666505/416172/fe17c07a-ac46-11e2-87f8-fd924d8d1b9d.jpg)
here, my firebug console
![network](https://f.cloud.github.com/assets/666505/416174/fe23a37c-ac46-11e2-88e0-694efc421055.jpg)
And here the network tab.

**Comment by joshribakoff** [comment]
We got this resolved. (I installed it for him as per his support contract).
