### ISSUE TITLE
Ensure no php short tags are used.

### ISSUE THREAD

**Issue by kylecannon** [vehiclefits/vfmagento#12]

**Comment by joshribakoff** [comment]
<?= will be always available in php 5.5, fyi.

**Comment by kylecannon** [comment]
Not an issue. But I feel that anything that is <? should be <?php <?= of course can stay.

**Comment by joshribakoff** [comment]
Agreed

**Comment by joshribakoff** [comment]
The following regex matches all instances of <? without giving false positives on <?xml or <?=
<\?(\s|\n|\t|[^a-zA-Z=])
