### ISSUE TITLE
Vaftest/ module for AJAX unit tests prevents manual testing & poses security threat if used in production

### ISSUE THREAD

**Issue by joshribakoff** [vehiclefits/vfmagento#13]
We have a module Vaftest/ it includes a controller which abuses Magento's global namespace for controller names. The intent behind this is as follows. Magento provides security checks for the admin controllers in preDispatch(). Any admin controller which extends Mage_Adminhtml_Controller_Action inherits a preDispatch() method that does multiple security checks, ensuring the user is logged in and a valid security token is passed. However when running qunit javascript unit tests, we want to skip all these security checks.

Therefore I created Vaftest, it adds a controller called Vehicleslist, which coincides with a controller in the Vaf module called Vehicleslist. Since "Vaftest" module comes after "Vaf" alphabetically, Magento loads it after. This means when users hit the URL /admin/vehicleslist, it uses the one from Vaftest, which overrides preDispatch() to skip the security checks.

This has the following adverse consequences. If the module is inadvertently used in production, anyone could gain access to the vehicles list page. In the past this was removed with a build script before being deployed, but now that we're open source, people should be able to check out the code & use it without having to run any build scripts.

Also, if the Vaftest module is present when doing manual browser based testing during development, since preDispatch() is overriden, the layout XML is not loaded. This produces an error in Magento that is hard to debug. The error states that certain Magento blocks are not found. This is because the layout XML is never loaded, since Vaftest's controller is being used which overrides preDispatch(). This caused us quite some grief when we ran into it, now I have gotten to the bottom of the issue so time to fix it!

**Comment by kylecannon** [comment]
So that's what it was! Makes sense!

**Comment by joshribakoff** [comment]
Actually it would not be too much of a security issue, since they would just get an error message. I'm thinking something like if we're running on localhost, then disable security checking. Otherwise we do the security check. However we want to be able to manually test & not get the error message. So I'm thinking have the ajax tests create a lock file in the tmp dir, if this lock file is present AND we're on localhost, then we disable the security check. If the lock file is not present, then we can detect that we're manually testing through the browser & not running unit tests through the browser. So any browser based unit tests must create a lock file before testing this page, and delete the lock file afterwards.
