### ISSUE TITLE
Recoverable Error : Import Vehicle Bolt Patterns

### ISSUE THREAD

**Issue by florian33** [vehiclefits/vfmagento#20]
I was trying to import Vehicle Bolt Patterns in your demo admin website
Recoverable Error: Argument 1 passed to Mage_Adminhtml_Controller_Action::_addContent() must be an instance of Mage_Core_Block_Abstract, boolean given, called in /nfs/c04/h03/mnt/165432/domains/demo.vehiclefits.com/html/app/code/local/Elite/Vafwheel/controllers/Admin/BoltController.php on line 34 and defined  in /nfs/c04/h03/mnt/165432/domains/demo.vehiclefits.com/html/app/code/core/Mage/Adminhtml/Controller/Action.php on line 120

I've the same problem on my server.

**Comment by joshribakoff** [comment]
When there is a PHP error, Magento suppresses it and throws this error instead basically. You can enabled developer mode in ./index.php to see the true error.

**Comment by florian33** [comment]
Well, i set developer mode in ./index.php but the message is the same.

**Comment by florian33** [comment]
i saw this is with developer mode on, when i comment 
//if (isset($_SERVER['MAGE_IS_DEVELOPER_MODE'])) {  //Mage::setIsDeveloperMode(true);} 
there is nothing that appear after import, i've a blank page...

**Comment by florian33** [comment]
I think the problem is in this line, in the createBlock but don't know between 'adminhtml/vaf_boltpatterns' and 'vaf/boltpatterns'  which is the error.

**Comment by florian33** [comment]
Find it in my exception.log, Some words are in french 

```
2013-04-26T13:29:40+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Type de bloc non valide: Elite_Vaflinks_Block_Cmslist' in /home/wizzo/public_html/app/Mage.php:595
Stack trace:
#0 /home/wizzo/public_html/app/code/local/Mage/Core/Model/Layout.php(495): Mage::throwException('Type de bloc no...')
#1 /home/wizzo/public_html/app/code/local/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('vaflinks/cmslis...', Array)
#2 /home/wizzo/public_html/app/code/local/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('vaflinks/cmslis...', 'vaf_cmslist')
#3 /home/wizzo/public_html/app/code/local/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('vaflinks/cmslis...', 'vaf_cmslist')
#4 /home/wizzo/public_html/app/code/local/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#5 /home/wizzo/public_html/app/code/local/Mage/Core/Model/Layout.php(210): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#6 /home/wizzo/public_html/app/code/local/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#7 /home/wizzo/public_html/app/code/core/Mage/Catalog/controllers/CategoryController.php(146): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#8 /home/wizzo/public_html/app/code/local/Mage/Core/Controller/Varien/Action.php(419): Mage_Catalog_CategoryController->viewAction()
#9 /home/wizzo/public_html/app/code/local/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('view')
#10 /home/wizzo/public_html/app/code/local/Mage/Core/Controller/Varien/Front.php(176): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /home/wizzo/public_html/app/code/local/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#12 /home/wizzo/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /home/wizzo/public_html/index.php(91): Mage::run('', 'store')
#14 {main}
```

**Comment by florian33** [comment]
Just for informations, Notes doesn't works too...

**Comment by florian33** [comment]
I try to map it directly in DB. In table "elite_definition_wheel", leaf_id is the id from table "elite_1_definition" Right ?
So i put one that currently exist and set lug_count, bolt_distance and offset.
I go to my website, and do my research BMW 750I 2008 bolt pattern set to 4x100.0=­> Nothing appears in Wheels / Mags 
But the wheel PF21782702573 is set to 4X100.0

**Comment by florian33** [comment]
Some hints for me to know where to search the problem ?

**Comment by joshribakoff** [comment]
You're asking many different unrelated things at once in this ticket. First of all we do not support manually inserting rows into the database table. The only supported use case of putting data into the system is using the user interface of the system, either the GUI or the CLI. Regarding the unknown block type see #25 Kyle has reproduced that and shown what the fix is.

**Comment by kylecannon** [comment]
Also in the future make one issue per error so we can have better track of what's going on and work on one thing at a time.

**Comment by florian33** [comment]
Good, but I don't want to create too much problems... I want to know if the problem is from my installlation or General...
Thanks for advices Guys !
