### ISSUE TITLE
Can't duplicate product with fitments

### ISSUE THREAD

**Issue by joshribakoff** [vehiclefits/vfmagento#28]
Getting a print_r() of an array. In the past this was tricky to unit test because it calls the parent method to duplicate the product, then duplicates the fitments. The solution should be to move duplication logic to a new method that simply accepts two product IDs, $from_product_id, $to_product_id.. just unit test that it copies the fitments from the old id to the new id. The unit test can insert two new products rather than actually use Magento's duplicate() method since it can't be tested easily.

**Comment by kylecannon** [comment]
If you're gonna move this into the "core" library i don't think a product id should be required in there. There may be instances where a product_id wont be used because someone is using it to filter YouTube videos that have a specific car type for example. Thoughts?

**Comment by kylecannon** [comment]
Maybe have a VF_Core VF_E-Commerce Core, and the Magento Module

**Comment by joshribakoff** [comment]
Sure it could be entity_id, and even be optional. You could just populate the vehicles list, and show all vehicles on the front-end unconditionally.

**Comment by joshribakoff** [comment]
If you're suggesting the notion that each feature that is optional should be in it's own repository I would have to disagree. Separating things into their own repositories adds complexities, and if the code often changes together it creates a more awkward work-flow... For example if one repo calls a function in another repo which needs to be renamed, we have a commit to each repo.. one commit in one repo to rename that function definition, and another commit in each repo that depends on it to rename the usages of that function.  Having  a class or two that's not used by some users is not a huge problem. Separating the core library into it's own repository only made sense because we want to be able to include that in more than one application. The Magento & Prestashop extensions both need the library. I'd almost be tempted to say both those extensions & the library should all be in one repository but I won't go as far as to say that. I like them in their own repositories but I feel like we should draw the line there to avoid an explosion of repositories.

**Comment by joshribakoff** [comment]
Not sure it made sense in the core library. Core library is just responsible for set/get fitments. Duplicating  products is a Magento specific hook. Not really clear on a way to write unit tests for it either without coupling those tests to Magento. Important part is that the core has unit tests for setting & getting fitments, which it does.
