### ISSUE TITLE
exception 'VF_Import_VehiclesList_CSV_Exception_FieldHeaders' with message

### ISSUE THREAD

**Issue by florian33** [vehiclefits/vfmagento#30]
here, my csv file :
MAKE,MODEL,START YEAR,END YEAR,BOLT PATTERN
Honda,Civic,1990,2005,4X100.0
Honda,Civic,2006,2013,4X114.3

2013-04-30T12:51:11+00:00 ERR (3): 
exception 'VF_Import_VehiclesList_CSV_Exception_FieldHeaders' with message 'Unable to locate field header for [make], perhaps not using comma delimiterArray
(
    [Make] => 0
    [MODEL] => 1
    [START YEAR] => 2
    [END YEAR] => 3
    [BOLT PATTERN] => 4
)
' in /home/wizzo/public_html/lib/VF/Import.php:151
Stack trace:
#0 /home/wizzo/public_html/lib/VF/Import/VehiclesList/CSV/Import.php(49): VF_Import->getFieldPositions()
#1 /home/wizzo/public_html/app/code/local/Elite/Vafwheel/Adminhtml/Block/Boltpatterns.php(37): VF_Import_VehiclesList_CSV_Import->import()
#2 /home/wizzo/public_html/app/code/local/Mage/Core/Model/Layout.php(491): Elite_Vafwheel_Adminhtml_Block_Boltpatterns->__construct(Array)
#3 /home/wizzo/public_html/app/code/local/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('adminhtml/vaf_b...', Array)
#4 /home/wizzo/public_html/app/code/local/Elite/Vafwheel/controllers/Admin/BoltController.php(32): Mage_Core_Model_Layout->createBlock('adminhtml/vaf_b...', 'vaf/boltpattern...')
#5 /home/wizzo/public_html/app/code/local/Mage/Core/Controller/Varien/Action.php(419): Elite_Vafwheel_Admin_BoltController->boltpatternsAction()
#6 /home/wizzo/public_html/app/code/local/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('boltpatterns')
#7 /home/wizzo/public_html/app/code/local/Mage/Core/Controller/Varien/Front.php(176): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#8 /home/wizzo/public_html/app/code/local/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#9 /home/wizzo/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#10 /home/wizzo/public_html/index.php(91): Mage::run('', 'store')
#11 {main}

**Comment by florian33** [comment]
If you want to check my file, https://mega.co.nz/#!pdYxhaJJ!DXtDQXgBTQcyM1fVNFcZpA6vGagdOTgwT79Cag_LK3U

**Comment by florian33** [comment]
I change all my columns name like this : make,model,start year,end year,bolt pattern

And i got this exceptions : 
2013-04-30T15:53:54+00:00 ERR (3): 
exception 'VF_Import_VehiclesList_CSV_Exception_FieldHeaders' with message 'Unable to locate field header for [year], perhaps not using comma delimiterArray
(
    [make] => 0
    [model] => 1
    [start year] => 2
    [end year] => 3
    [bolt pattern] => 4
)
' in /home/wizzo/public_html/lib/VF/Import.php:151
Stack trace:
#0 /home/wizzo/public_html/lib/VF/Import/VehiclesList/CSV/Import.php(49): VF_Import->getFieldPositions()
#1 /home/wizzo/public_html/app/code/local/Elite/Vafwheel/Adminhtml/Block/Boltpatterns.php(37): VF_Import_VehiclesList_CSV_Import->import()
#2 /home/wizzo/public_html/app/code/local/Mage/Core/Model/Layout.php(491): Elite_Vafwheel_Adminhtml_Block_Boltpatterns->__construct(Array)
#3 /home/wizzo/public_html/app/code/local/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('adminhtml/vaf_b...', Array)
#4 /home/wizzo/public_html/app/code/local/Elite/Vafwheel/controllers/Admin/BoltController.php(32): Mage_Core_Model_Layout->createBlock('adminhtml/vaf_b...', 'vf/vaf/boltpatt...')
#5 /home/wizzo/public_html/app/code/local/Mage/Core/Controller/Varien/Action.php(419): Elite_Vafwheel_Admin_BoltController->boltpatternsAction()
#6 /home/wizzo/public_html/app/code/local/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('boltpatterns')
#7 /home/wizzo/public_html/app/code/local/Mage/Core/Controller/Varien/Front.php(176): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#8 /home/wizzo/public_html/app/code/local/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#9 /home/wizzo/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#10 /home/wizzo/public_html/index.php(91): Mage::run('', 'store')
#11 {main}

It seems looking for import a vehicle.

**Comment by joshribakoff** [comment]
Rename to year_start & year_end

**Comment by florian33** [comment]
GOT IT, So Just modify you doc for header columns lie this : 
make,model,year_start,year_end,bolt pattern

Thanks Josh !
