### ISSUE TITLE
Moving modules to respective repositories

### ISSUE THREAD

**Issue by kylecannon** [vehiclefits/vfmagento#31]
I feel that all the magento modules such as Vafpaint and Vaftire should have all their business logic moved to respective repositories and use composer to require them. For example, my company doesn't need Vaftire and Vafpaint so it's kind of pointless for me to have to have that code base in my magento installation. This will also add better ease of big management on a module by module basis.

**Comment by joshribakoff** [comment]
It also complicates development, we have to test with different combinations of those modules present. I'm open to it but its not a high priority, those things being present do not hurt anything but Im on the same page as you

**Comment by joshribakoff** [comment]
Zend Framework 2 offers many different packages via composer which are all hosted in one repository. I think we should do it that way, see my notes in the other issue you opened about multiple repos.
