### ISSUE TITLE
Enhancement : How to delete wrong bolt pattern Mapping !

### ISSUE THREAD

**Issue by florian33** [vehiclefits/vfmagento#33]
When we set a wrong bolt pattern for a vehicle and we import, it map vehicle to a wheel
And when we change the bolt pattern, the wrong one stay set to the product.

Maybe, find a way to change it...

**Comment by joshribakoff** [comment]
The wrong what stays set to the product? You have to delete the mappings & the bolt pattern in one step.. let me know if you tried that & it didn't work.

**Comment by florian33** [comment]
In fact, first, i set Honda Civic 2005-2010 with a 4X100.0.
Later, My boss told me it's 5X114.3. So i change it in my csv file and re-import it.
But when i search for Honda Civic 2010, i still have wheels with a 4X100.0 that appears.

**Comment by joshribakoff** [comment]
When you set the bolt pattern it adds the matching vehicles. If you wanted to delete a vehicle you need to do that yourself.

**Comment by florian33** [comment]
Ok, maybe let it know the user.

**Comment by joshribakoff** [comment]
Elaborated on this in the documentation.

**Comment by florian33** [comment]
In the future, maybe create a delete method with the sku and the vehicle that we want unmatched ? :)
