### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Dylan-Bogusz** [vehiclefits/vfmagento#34]
I'm trying to install this extension for my company's website. We are currently on Magento Enterprise Version 1.12.03. I extracted the zip folder that I download here. "Vehicle-Fits-Magento-master.zip" I extracted the folder to my computer and copied the contents to my root server folder where magento is installed. It asked me to overwrite a file in the app folder. "name.phtml" so i did. Followed the other instructions.Renamed config.default.ini to config.ini in the app/code/local/Elite/Vaf/ folder. then I added this line of code"require_once( 'code/local/Elite/Vaf/bootstrap.php' ); " to the mage.php file. The vf-install.php file was already there since I copied over the whole contents from the the zip I originally downloaded from here. I went to my browser and pointed to that file to install and got this error.

Warning: require_once(lib/VF/Schema/Generator.php): failed to open stream: No such file or directory in /chroot/home/motocros/motocrossgiant.com/html/vf-install.php on line 28 Fatal error: require_once(): Failed opening required 'lib/VF/Schema/Generator.php' (include_path='/chroot/home/motocros/motocrossgiant.com/html/app/code/local:/chroot/home/motocros/motocrossgiant.com/html/app/code/community:/chroot/home/motocros/motocrossgiant.com/html/app/code/core:/chroot/home/motocros/motocrossgiant.com/html/lib::/chroot/home/motocros/motocrossgiant.com/html/lib/Vehicle-Fits-Core/library/:.:/usr/share/pear:/usr/share/php') in /chroot/home/motocros/motocrossgiant.com/html/vf-install.php on line 28

Now i get a 500 server error when i try to log into our admin page. What did i do wrong? Thanks!

**Comment by joshribakoff** [comment]
Use the download link on vehiclefits.com not github.

**Comment by joshribakoff** [comment]
This happens because the VF library is a git submodule. Github doesn't add the submodule files, a recursive git checkout would. Or you could just use the .zip we created on the vehiclefits.com site that already has all the files.

**Comment by Dylan-Bogusz** [comment]
I think there is something wrong with your build44 zip file. Its very small and appears to be incomplete.

**Comment by joshribakoff** [comment]
Thanks - you're right the .zip has all empty folders. The .tar.gz is correct though. I will fix this.
