### ISSUE TITLE
Migrate bootstrap to magento observer event.

### ISSUE THREAD

**Issue by kylecannon** [vehiclefits/vfmagento#36]
Remove need to include bootstrap in app/Mage.php & hook a Magento even instead. As per discussed, we think controller_action_predispatch will do

**Comment by joshribakoff** [comment]
There's a better event called controller_front_init_before and I tested setting up a hook for that & moving the bootstrap.php code there, it works great. This will also give us the opportunity to inject things like base paths & URLs, and the config object into VF_Singleton from within the event hook. This way VF_Singleton won't have code like this:

```
function processUrl()
{
    // prestashop
    if(defined('_PS_VERSION_')) {
        return '/modules/vaf/process.php?';
    }
    // magento
    return $this->getBaseUrl(isset($_SERVER['HTTPS'])) . '/vaf/ajax/process?';
}
```

Instead we'll simply inject the "process url" into VF_Singleton from within the bootstrap event, the VF_Singleton will just work more like a registry then doing work.
