### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by JordyT** [vehiclefits/vfmagento#39]
I'm trying to install the Magento VF plug-in with the code from the latest git commit. When I try to run /vf-install.php, I get the following error...

Fatal error: Class 'Elite_Vaf_Helper_Data' not found in C:\Zend\Apache2\htdocs\magento.local\vf-install.php on line 30

I'm running Magento CE v1.7.0.2.

Any ideas?

**Comment by joshribakoff** [comment]
Thanks looks like that file didn't get committed, I'll fix this asap

**Comment by JordyT** [comment]
Great, thanks!

**Comment by JordyT** [comment]
I really hate to be a pest, but do you know when that file will be committed? I'm really anxious to try this extension. :)

**Comment by joshribakoff** [comment]
You can use the download links here: http://vehiclefits.com/download
They are correct, the issue exists in git only and does not exist in any released version of the software.

**Comment by JordyT** [comment]
I actually tried that first, but the app, lib, skin and vf-documentation directories kept coming up empty. That's why I was trying the git version. However, upon further research, I've discovered that issue only exists within the zip downloads, and not the tar.gz. So, now I'm going to try this out, using the tar.gz version of v2-build44.

Thanks!
