### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'wizzo.elite_mapping' doesn't exist

### ISSUE THREAD

**Issue by florian33** [vehiclefits/vfmagento#43]
Hi,

When i tried to delete a product in the admin pane, i got this error :
"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'wizzo.elite_mapping' doesn't exist" but when i took a look in my DB, i've this table "elite_1_mapping".

Something to change ?

**Comment by joshribakoff** [comment]
Where is the PHP filename & line number part of the error message? Please show the complete error message

**Comment by florian33** [comment]
![problem delete](https://f.cloud.github.com/assets/666505/644828/af9daf0a-d396-11e2-8993-5dba53834150.jpg)

That the only message I get....

**Comment by florian33** [comment]
That become serious, i can't delete products.... I have to disable the product instead of delete !!

**Comment by joshribakoff** [comment]
This was already fixed April 26th, 2 months ago...
29d19c8

**Comment by joshribakoff** [comment]
Just realized that commit introduced a new issue though, #50 for example when deleting category ID 3, it removes the fitments from product ID 3 ... I will have to make sure that gets fixed asap. That method was missing unit tests which could have prevented these regressions, I'm working on creating unit tests.
