### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shrikant_mage611.elite_mapping' doesn't exist

### ISSUE THREAD

**Issue by ridesafer** [vehiclefits/vfmagento#51]
This is as far as the error message goes when attempting to delete a product from the database. Not sure where to go from here.

![capture](https://f.cloud.github.com/assets/5239262/970707/f560ad8c-05da-11e3-9136-f3d6d73a1262.JPG)

**Comment by joshribakoff** [comment]
Duplicate of #43

**Comment by ridesafer** [comment]
But that post doesn't outline what the fix was. Could you point me in the right direction?
