### ISSUE TITLE
Error in vf-install.php

### ISSUE THREAD

**Issue by halflife3br** [vehiclefits/vfmagento#61]
I downloaded the last commit at github and trying to install the magento plugin, but the vf-install.php generates the following error: 

Warning: require_once(/home/beta/public_html/app/code/local/Elite/Vaf/../vendor/autoload.php): failed to open stream: No such file or directory in /home/beta/public_html/app/code/local/Elite/Vaf/bootstrap.php on line 31 Fatal error: require_once(): Failed opening required '/home/beta/public_html/app/code/local/Elite/Vaf/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /home/beta/public_html/app/code/local/Elite/Vaf/bootstrap.php on line 31

Anyone ever seen this error?
![error](https://f.cloud.github.com/assets/5540283/1213095/5d1713b8-2623-11e3-8ea4-873d98c062e4.jpg)

**Comment by joshribakoff** [comment]
This is not a bug in our code you just did not install composer yet

**Comment by halflife3br** [comment]
Thank for the reply.
My mistake. Was trying to install in the old way! 

I followed the instructions for new installation, however when I run "php bin / vfmagento schema" it's an error in the console:

PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in /home/beta/public_html/app/code/local/Elite/vendor/kylecannon/magento/lib/Zend/Db/Adapter/Pdo/Abstract.php:129
Stack trace:
#0 /home/beta/public_html/app/code/local/Elite/vendor/kylecannon/magento/lib/Zend/Db/Adapter/Pdo/Abstract.php(129): PDO->__construct('mysql:dbname=ma...', 'root', '', Array)
#1 /home/beta/public_html/app/code/local/Elite/vendor/kylecannon/magento/lib/Zend/Db/Adapter/Pdo/Mysql.php(96): Zend_Db_Adapter_Pdo_Abstract->_connect()
#2 /home/beta/public_html/app/code/local/Elite/vendor/kylecannon/magento/lib/Zend/Db/Adapter/Abstract.php(315): Zend_Db_Adapter_Pdo_Mysql->_connect()
#3 /home/beta/public_html/app/code/local/Elite/vendor/vehiclefits/vehicle-fits-core/library/VF/Singleton.php(242): Zend_Db_Adapter_Abstract->getConnection()
#4 /home/beta/public_html/app/code/local/Elite/vendor/vehiclefits/vehicle-fits-core/library/VF/CLI.php(73): VF_Singleton->setRea in /home/beta/public_html/app/code/local/Elite/vendor/kylecannon/magento/lib/Zend/Db/Adapter/Pdo/Abstract.php on line 144

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in /home/beta/public_html/app/code/local/Elite/vendor/kylecannon/magento/lib/Zend/Db/Adapter/Pdo/Abstract.php:129
Stack trace:
#0 /home/beta/public_html/app/code/local/Elite/vendor/kylecannon/magento/lib/Zend/Db/Adapter/Pdo/Abstract.php(129): PDO->__construct('mysql:dbname=ma...', 'root', '', Array)
#1 /home/beta/public_html/app/code/local/Elite/vendor/kylecannon/magento/lib/Zend/Db/Adapter/Pdo/Mysql.php(96): Zend_Db_Adapter_Pdo_Abstract->_connect()
#2 /home/beta/public_html/app/code/local/Elite/vendor/kylecannon/magento/lib/Zend/Db/Adapter/Abstract.php(315): Zend_Db_Adapter_Pdo_Mysql->_connect()
#3 /home/beta/public_html/app/code/local/Elite/vendor/vehiclefits/vehicle-fits-core/library/VF/Singleton.php(242): Zend_Db_Adapter_Abstract->getConnection()
#4 /home/beta/public_html/app/code/local/Elite/vendor/vehiclefits/vehicle-fits-core/library/VF/CLI.php(73): VF_Singleton->setRea in /home/beta/public_html/app/code/local/Elite/vendor/kylecannon/magento/lib/Zend/Db/Adapter/Pdo/Abstract.php on line 144

The script should use the Mysql User/Password in the magento files???

The vf-install.php generates the Fatal error: Call to a member function getModelInstance() on a non-object in /home/beta/public_html/app/Mage.php on line 463

Magento Home and Admin is totally blank... 

Thanks in advanced

**Comment by joshribakoff** [comment]
Both the command line & web installers [should] use the credentials from magento,

see here: https://github.com/vehiclefits/Vehicle-Fits-Magento/blob/master/app/code/local/Elite/Vaf/bootstrap.php#L33-L35 and here: https://github.com/vehiclefits/Vehicle-Fits-Magento/blob/master/app/code/local/Elite/bin/vfmagento#L37-L46

Regarding your last error, it seems like it could just be a problem with Magento itself not our code based on this thread - http://www.magentocommerce.com/boards/viewthread/38108/

Regarding the blank pages, it sounds like you need to view your error log to see the errors. Either way, the code in GitHub is for development, and the official supported distribution is here http://vehiclefits.com/download

**Comment by kylecannon** [comment]
Also make sure that you don't have any security modules enabled. Since `putenv()` and `getenv()` is used for some functions in the database injection it might not allow you to use those functions.

**Comment by halflife3br** [comment]
Thanks for the replies. 

I found the error of blank page, as I followed the "original" installation process, I put the require in Mage.php! I removed the line and Magento worked, installed the database with the vf-install.php.

The last question: On installation I needed to enable parse_ini_file in PHP, I can disable this feature?

Thanks in advanced!

**Comment by joshribakoff** [comment]
Not sure why you needed that enabled. Our extension does not require it.

**Comment by kylecannon** [comment]
Did you clear the cache? we use a magento event to bootstrap instead now.

**Comment by halflife3br** [comment]
Because the error in Report:  parse_ini_file() has been disabled for security reasons";i:1;s:3439:"#0 /home/beta/public_html/app/code/local/Elite/vendor/kylecannon/magento/lib/Zend/Config/Ini.php(201): Zend_Config_Ini->_parseIniFile('/home/beta/publ...') 

i dont know, but after that enabled the parse_ini_file function in php.ini, the module was installed normally and working everything fine ..

Thank you!

**Comment by joshribakoff** [comment]
Thanks that makes sense now. I guess Zend framework requires that setting.
I think it's enabled by default though.
