### ISSUE TITLE
Upgrade-vaf.php

### ISSUE THREAD

**Issue by florian33** [vehiclefits/vfmagento#9]
![Upgrading](https://f.cloud.github.com/assets/666505/410096/27ad41a4-ab65-11e2-8976-2eae2ae13a72.png)
then when I press go,
"1_create_schema_tbl.php
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'elite_schema' already exists' in ROOT_FOLDER\lib\Zend\Db\Statement\Pdo.php:228 Stack trace: #0 ROOT_FOLDER\lib\Zend\Db\Statement\Pdo.php(228): PDOStatement->execute(Array) #1 ROOT_FOLDER\lib\Zend\Db\Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array) #2 ROOT_FOLDER\lib\Zend\Db\Adapter\Abstract.php(479): Zend_Db_Statement->execute(Array) #3 ROOT_FOLDER\lib\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('CREATE TABLE `e...', Array) #4 ROOT_FOLDER\app\code\local\Elite\Vaf\sql\migrations\1_create_schema_tbl.php(30): Zend_Db_Adapter_Pdo_Abstract->query('CREATE TABLE`e...') #5 ROOT_FOLDER\app\code\local\Elite\Vafinstall\MigrateBase.php(152): require('C:\xampp\htdocs...') #6 ROOT_FOLDER\app\code\local\Elite\Vafinstall\MigrateBase.php(93): Elite_Vafinstall_MigrateBase->runScript('1', 'C:\xampp\htdocs...') in ROOT_FOLDER\lib\Zend\Db\Statement\Pdo.php on line 234

**Comment by kylecannon** [comment]
You need to export your figments and reimport them after running the installer. Version 2 has no upgrade script.

**Comment by florian33** [comment]
Well, I test in 2 ways.
First, when I installed, i tried with "Run database SQL". All DB were not create and with upgrade that give me the last message error. So, I tried to re-install and copy/paste the SQL code and that created all tables. Then, I use upgrade-vaf.php and the Upgrade works well.
And now, error when trying to manage vehicule list...
For informations, I haven't any models or something else. it's from new magento install.

**Comment by kylecannon** [comment]
So is it working now? Keep in mind we're making lots of upgrades and changes at the moment so let us know if you find any more issues. We have lots of big plans in the future.

**Comment by florian33** [comment]
Here is my log whent trying to manage vehicule list :
a:5:{i:0;s:130:"parse_ini_file(C:\xampp\htdocs\bolt\app\code\local\Elite\Vaf/..//Vaf/config.ini): failed to open stream: No such file or directory";i:1;s:3220:"#0 C:\xampp\htdocs\bolt\lib\Zend\Config\Ini.php(201): Zend_Config_Ini->_parseIniFile('C:\xampp\htdocs...')

**Comment by kylecannon** [comment]
go to app/code/local/Elite/Vaf and copy config.default.ini to config.ini

**Comment by florian33** [comment]
Ok, It's ok for this ! Thanks you.
